name: Docker Image CI

# When to run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:            # Creates a button to execute from outside of repo
    inputs:
      image_version:
        description: 'Please specify a version'
        required: false
        default: "latest"







jobs:

  build:

    runs-on: ubuntu-latest

    steps:


      - name: Checkout 
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tools/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tools:latest














